language: go

go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"
  - tip

sudo: false

before_install:
  - go get goa.design/goa/v3/...

script:
  - go test ./...
  - cd testdata; goa gen calc/design; go test ./...; cd ..
