name: Go

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        go: ['1.14.x', '1.15.x', '1.16.x']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          path: src/github.com/ikawaha/goahttpcheck

      - name: Build
        run: go build -v ./...
        working-directory: src/github.com/ikawaha/goahttpcheck

      - name: Test
        env:
          GO111MODULE: on
          GOPATH:
        run: |
          go list ./...
          go build -o goa goa.design/goa/v3/cmd/goa
          ./goa version
          ./goa gen calc/example
          go test -v ./...
        working-directory: src/github.com/ikawaha/goahttpcheck/testdata
