name: goa gen
on:
  pull_request:
    paths:
      - go.mod
      - go.sum
      - '**.go'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: goa gen
        run: |
          make goa_gen
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: goa gen
          branch: ${{ github.head_ref }}
      - name: test
        run: |
          cd testdata && go test ./...