name: goa gen
on:
  pull_request:
    paths:
      - go.mod
      - go.sum
      - '**.go'
  workflow_dispatch:
jobs:
  build:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod
      - name: goa gen
        run: |
          make goa_gen
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: goa gen
          branch: ${{ github.head_ref }}
      - name: test
        run: |
          cd testdata && go test ./...
